name: MacOS
on: 
  push:
    branches: master
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip --version
          pip install sphinx==1.6.7 
          pip install sphinxcontrib-bibtex sphinx_inline_tabs sphinx_sitemap
      - name: build manual
        run: |
          ls ./
          pwd
