name: MacOS
on: 
  push:
    branches: master
jobs:
  test:
    name: html
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip --version
          pip install sphinx==1.6.7 
          pip install sphinxcontrib-bibtex sphinx_inline_tabs sphinx_sitemap
      # need checkout to copy the latest source files to the current path
      - uses: actions/checkout@v2
      - name: build manual
        run: |
          ls .
          sphinx-build -b html sphinx/source public
          sphinx-build -b latex sphinx/source public/latex
      - uses: docker://laurenss/texlive-full
      - name: build latex
        uses: dante-ev/latex-action@master
        with:
          root_file: public/latex/OpenFOAM算例详解_latest.tex
          compiler: xelatex
          working_directory: public/latex
      - name: check latex
        run: |
          xelatex --version
          latexmk --version
      - uses: actions/upload-artifact@v2
        with:
          name: manual.zip
          path: pages
