name: MacOS
on: 
  push:
    branches: master
jobs:
  test:
    name: test
    runs-on: macos-latest
    steps:
      - name: step1
        run: pip install sphinx==1.6.7
      - name: step2
        run: mkdir build